### ISSUE TITLE
make routing works after a page refresh

### ISSUE THREAD

**Issue by IAfanasovMob** [I-OWE-YOU/aws-backend#83]
Now http://tegoedje-dev.s3-website-eu-west-1.amazonaws.com/let-me-help returns 404
need to both dev and prod

**Comment by petarblazevski** [comment]
This link is from S3 and not CloudFront. This is the expected behavior. We need to restrict access to this link because it's an S3 bucket link. And it doesn't even have HTTPS

**Comment by IAfanasovMob** [comment]
incorrect testing
